export enum AuthErrorCode {
  API_KEY_DISABLED = 'API_KEY_DISABLED',
  API_KEY_EXPIRED = 'API_KEY_EXPIRED',
  API_KEY_NOT_FOUND = 'API_KEY_NOT_FOUND',
  API_KEY_INVALID = 'API_KEY_INVALID',
  API_KEY_MISSING = 'API_KEY_MISSING',
}
