export enum ValidationErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_POOL_ADDRESS = 'INVALID_POOL_ADDRESS',
  UNSUPPORTED_CHAIN_ID = 'UNSUPPORTED_CHAIN_ID',
  INVALID_PAGINATION_CURSOR = 'INVALID_PAGINATION_CURSOR',
  INVALID_BLOCKCHAIN_ADDRESS = 'INVALID_BLOCKCHAIN_ADDRESS',
  INVALID_PROTOCOL_ID = 'INVALID_PROTOCOL_ID',
}
