import { ZERO_ETHEREUM_ADDRESS } from './constants';
import { MultichainTokenDTO } from './dtos/multi-chain-token.dto';
import { Networks } from './enums/networks';

export const tokenList: MultichainTokenDTO[] = [
  {
    id: '1',
    name: 'Ethereum',
    symbol: 'ETH',
    addresses: {
      [Networks.ETHEREUM]: ZERO_ETHEREUM_ADDRESS,
      [Networks.SCROLL]: ZERO_ETHEREUM_ADDRESS,
      [Networks.SEPOLIA]: ZERO_ETHEREUM_ADDRESS,
      [Networks.BASE]: ZERO_ETHEREUM_ADDRESS,
      [Networks.UNICHAIN]: ZERO_ETHEREUM_ADDRESS,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: '0x2170Ed0880ac9A755fd29B2688956BD959F933F8',
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: 18,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: 18,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: 18,
    },
    logoUrl: 'https://assets-cdn.trustwallet.com/blockchains/ethereum/info/logo.png',
  },
  {
    id: '2',
    name: 'Wrapped Ethereum',
    symbol: 'WETH',
    addresses: {
      [Networks.ETHEREUM]: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
      [Networks.SCROLL]: '0x5300000000000000000000000000000000000004',
      [Networks.SEPOLIA]: '0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14',
      [Networks.BASE]: '0x4200000000000000000000000000000000000006',
      [Networks.UNICHAIN]: '0x4200000000000000000000000000000000000006',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: '0x9895d81bb462a195b4922ed7de0e3acd007c32cb',
      // [Networks.BNB]: '0x2170Ed0880ac9A755fd29B2688956BD959F933F8',
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: 18,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: 18,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: 18,
      // [Networks.BNB]: 18,
    },
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
  },
  {
    id: '3',
    name: 'Tether',
    symbol: 'USDT',
    addresses: {
      [Networks.ETHEREUM]: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
      [Networks.SCROLL]: '0xf55BEC9cafDbE8730f096Aa55dad6D22d44099Df',
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2',
      [Networks.UNICHAIN]: '0x588CE4F028D8e7B53B687865d6A67b3A54C75518',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: '0x55d398326f99059ff775485246999027b3197955',
    },
    decimals: {
      [Networks.ETHEREUM]: 6,
      [Networks.SCROLL]: 6,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 6,
      [Networks.UNICHAIN]: 6,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: 18,
    },
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
  },
  {
    id: '4',
    name: 'USDC',
    symbol: 'USDC',
    addresses: {
      [Networks.ETHEREUM]: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      [Networks.SCROLL]: '0x06eFdBFf2a14a7c8E15944D1F4A48F9F95F663A4',
      [Networks.SEPOLIA]: '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238',
      [Networks.BASE]: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
      [Networks.UNICHAIN]: '0x078d782b760474a361dda0af3839290b0ef57ad6',
      [Networks.HYPER_EVM]: '0xb88339cb7199b77e23db6e890353e22632ba630f',
      [Networks.PLASMA]: null,
      // [Networks.BNB]: '0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d',
    },
    decimals: {
      [Networks.ETHEREUM]: 6,
      [Networks.SCROLL]: 6,
      [Networks.SEPOLIA]: 6,
      [Networks.BASE]: 6,
      [Networks.UNICHAIN]: 6,
      [Networks.HYPER_EVM]: 6,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: 18,
    },
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
  },
  {
    id: '5',
    name: 'Wrapped Bitcoin',
    symbol: 'WBTC',
    addresses: {
      [Networks.ETHEREUM]: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
      [Networks.SCROLL]: '0x3c1bca5a656e69edcd0d4e36bebb3fcdaca60cf1',
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0x0555E30da8f98308EdB960aa94C0Db47230d2B9c',
      [Networks.UNICHAIN]: '0x0555E30da8f98308EdB960aa94C0Db47230d2B9c',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 8,
      [Networks.SCROLL]: 8,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 8,
      [Networks.UNICHAIN]: 8,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: null,
    },
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599/logo.png',
  },
  {
    id: '6',
    name: 'Coinbase Wrapped Bitcoin',
    symbol: 'cbBTC',
    addresses: {
      [Networks.ETHEREUM]: '0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 8,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 8,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: null,
    },
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/200x200/32994.png',
  },
  {
    id: '7',
    name: 'DAI',
    symbol: 'DAI',
    addresses: {
      [Networks.ETHEREUM]: '0x6b175474e89094c44da98b954eedeac495271d0f',
      [Networks.SCROLL]: '0xca77eb3fefe3725dc33bccb54edefc3d9f764f97',
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: '0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3',
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: 18,
    },
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
  },
  {
    id: '8',
    name: 'tBTC',
    symbol: 'tBTC',
    addresses: {
      [Networks.ETHEREUM]: '0x18084fbA666a33d37592fA2633fD49a74DD93a88',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0x236aa50979d5f3de3bd1eeb40e81137f22ab794b',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: null,
    },
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/200x200/26133.png',
  },
  {
    id: '9',
    name: 'Lombard Staked BTC',
    symbol: 'LBTC',
    addresses: {
      [Networks.ETHEREUM]: '0x8236a87084f8B84306f72007F36F2618A5634494',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0xecac9c5f704e954931349da37f60e39f515c11c1',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: '0xecac9c5f704e954931349da37f60e39f515c11c1',
    },
    decimals: {
      [Networks.ETHEREUM]: 8,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 8,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: 8,
    },
    logoUrl: 'https://img.cryptorank.io/coins/lombard_staked_btc1725876587975.png',
  },
  {
    id: '10',
    name: 'Uniswap',
    symbol: 'UNI',
    addresses: {
      [Networks.ETHEREUM]: '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984',
      [Networks.SCROLL]: '0x434cdA25E8a2CA5D9c1C449a8Cb6bCbF719233E8',
      [Networks.SEPOLIA]: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984',
      [Networks.BASE]: '0xc3De830EA07524a0761646a6a4e4be0e114a3C83',
      [Networks.UNICHAIN]: '0x8f187aA05619a017077f5308904739877ce9eA21',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: '0xbf5140a22578168fd562dccf235e5d43a02ce9b1',
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: 18,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: 18,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: 18,
    },
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984/logo.png',
  },
  {
    id: '11',
    name: 'Chainlink',
    symbol: 'LINK',
    addresses: {
      [Networks.ETHEREUM]: '0x514910771af9ca656af840dff83e8264ecf986ca',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: '0x779877A7B0D9E8603169DdbD7836e478b4624789',
      [Networks.BASE]: '0x88Fb150BDc53A65fe94Dea0c9BA0a6dAf8C6e196',
      [Networks.UNICHAIN]: '0x5a53B6D19D8EDCb7923F0D840EeBB3f09BBeEfB7',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: '0xf8a0bf9cf54bb92f17374d9e9a321e6a111a51bd',
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: 18,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: 18,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: 18,
    },
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x514910771AF9Ca656af840dff83E8264EcF986CA/logo.png',
  },
  {
    id: '12',
    name: 'Aave',
    symbol: 'AAVE',
    addresses: {
      [Networks.ETHEREUM]: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9',
      [Networks.SCROLL]: '0x79379c0e09a41d7978f883a56246290ee9a8c4d3',
      [Networks.SEPOLIA]: '0x88541670E55cC00bEEFD87eB59EDd1b7C511AC9a',
      [Networks.BASE]: '0x63706e401c06ac8513145b7687A14804d17f814b',
      [Networks.UNICHAIN]: '0x02a24C380dA560E4032Dc6671d8164cfbEEAAE1e',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: '0xfb6115445bff7b52feb98650c87f44907e58f802',
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: 18,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: 18,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: 18,
    },
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9/logo.png',
  },
  {
    id: '13',
    name: 'Scroll',
    symbol: 'SCR',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: '0xd29687c813D741E2F938F4aC377128810E217b1b',
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: null,
    },
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/200x200/26998.png',
  },
  {
    id: '14',
    name: 'EURC',
    symbol: 'EURC',
    addresses: {
      [Networks.ETHEREUM]: '0x1abaea1f7c830bd89acc67ec4af516284b1bc33c',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0x60a3e35cc302bfa44cb288bc5a4f316fdb1adb42',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 6,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 6,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
      // [Networks.BNB]: null,
    },
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x1aBaEA1f7C830bD89Acc67eC4af516284b1bC33c/logo.png',
  },
  {
    id: '15',
    name: 'First Digital USD',
    symbol: 'FDUSD',
    addresses: {
      [Networks.ETHEREUM]: '0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409',
      // [Networks.BNB]: '0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409/logo.png',
  },
  {
    id: '16',
    name: 'Wrapped BNB',
    symbol: 'WBNB',
    addresses: {
      [Networks.ETHEREUM]: '0xb8c77482e45f1f44de1745f52c74426c631bdd52',
      // [Networks.BNB]: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    logoUrl: 'https://assets-cdn.trustwallet.com/blockchains/binance/info/logo.png',
  },
  {
    id: '17',
    name: 'BNB',
    symbol: 'BNB',
    decimals: {
      [Networks.ETHEREUM]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    logoUrl: 'https://assets-cdn.trustwallet.com/blockchains/binance/info/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0xb8c77482e45f1f44de1745f52c74426c631bdd52',
      // [Networks.BNB]: zeroEthereumAddress,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '18',
    name: 'PancakeSwap',
    symbol: 'CAKE',
    addresses: {
      [Networks.ETHEREUM]: '0x152649eA73beAb28c5b49B26eb48f7EAD6d4c898',
      // [Networks.BNB]: '0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0x3055913c90Fcc1A6CE9a358911721eEb942013A1',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x152649eA73beAb28c5b49B26eb48f7EAD6d4c898/logo.png',
  },
  {
    id: '19',
    name: 'BTCB Token',
    symbol: 'BTCB',
    addresses: {
      [Networks.ETHEREUM]: null,
      // [Networks.BNB]: '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    logoUrl: 'https://assets-cdn.trustwallet.com/blockchains/binance/assets/BTCB-1DE/logo.png',
  },
  {
    id: '20',
    name: 'World Liberty Financial USD',
    symbol: 'USD1',
    addresses: {
      [Networks.ETHEREUM]: '0x8d0D000Ee44948FC98c9B98A4FA4921476f08B0d',
      // [Networks.BNB]: '0x8d0D000Ee44948FC98c9B98A4FA4921476f08B0d',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x8d0D000Ee44948FC98c9B98A4FA4921476f08B0d/logo.png',
  },
  {
    id: '21',
    name: 'SolvBTC',
    symbol: 'SolvBTC',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/200x200/33312.png',
    addresses: {
      [Networks.ETHEREUM]: '0x7a56e1c57c7475ccf742a1832b028f0456652f97',
      // [Networks.BNB]: '0x4aae823a6a0b376De6A78e74eCC5b079d38cBCf7',
      [Networks.SCROLL]: '0x3ba89d490ab1c0c9cc2313385b30710e838370a4',
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0x3B86Ad95859b6AB773f55f8d94B4b9d443EE931f',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '22',
    name: 'Toncoin',
    symbol: 'TON',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x582d872A1B094FC48F5DE31D3B73F2D9bE47def1/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0x582d872a1b094fc48f5de31d3b73f2d9be47def1',
      // [Networks.BNB]: '0x76a797a59ba2c17726896976b7b3747bfd1d220f',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 9,
      // [Networks.BNB]: 9,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '23',
    name: 'RZUSD',
    symbol: 'RZUSD',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/200x200/35716.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      // [Networks.BNB]: '0xc4a1cc5ca8955a4650bdc109bddf110e33a1e344',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '24',
    name: 'Liquity USD',
    symbol: 'LUSD',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x5f98805A4E8be255a32880FDeC7F6728C6568bA0/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0x5f98805A4E8be255a32880FDeC7F6728C6568bA0',
      // [Networks.BNB]: '0x5bb4d589467c25A5Ac8db930372dc5dA30C3410E',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0x368181499736d0c0cc614dbb145e2ec1ac86b8c6',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '25',
    name: 'Sky Dollar',
    symbol: 'USDS',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xdC035D45d973E3EC169d2276DDab16f1e407384F/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0xdC035D45d973E3EC169d2276DDab16f1e407384F',
      [Networks.BASE]: '0x820c137fa70c8691f0e44dc420a5e53c168921dc',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '26',
    name: 'Ethena USDe',
    symbol: 'USDe',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x4c9EDD5852cd905f086C759E8383e09bff1E68B3/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0x4c9EDD5852cd905f086C759E8383e09bff1E68B3',
      [Networks.BASE]: '0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34',
      // [Networks.BNB]: '0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34',
      [Networks.SCROLL]: '0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34',
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34',
      [Networks.PLASMA]: '0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34',
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: 18,
    },
  },
  {
    id: '27',
    name: 'Decentralized USD',
    symbol: 'USDD',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x3D7975EcCFc61a2102b08925CbBa0a4D4dBB6555/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0x3D7975EcCFc61a2102b08925CbBa0a4D4dBB6555',
      [Networks.BASE]: null,
      // [Networks.BNB]: '0x392004BEe213F1FF580C867359C246924f21E6Ad',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '28',
    name: 'TrueUSD',
    symbol: 'TUSD',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0x0000000000085d4780B73119b644AE5ecd22b376',
      [Networks.BASE]: null,
      // [Networks.BNB]: '0x40af3827F39D0EAcBF4A168f8D4ee67c121D11c9',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '29',
    name: 'Frax USD',
    symbol: 'frxUSD',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/36039.png',
    addresses: {
      [Networks.ETHEREUM]: '0xCAcd6fd266aF91b8AeD52aCCc382b4e165586E29',
      [Networks.BASE]: '0xe5020a6d073a794b6e7f05678707de47986fb0b6',
      // [Networks.BNB]: '0x80Eede496655FB9047dd39d9f418d5483ED600df',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: '0x80eede496655fb9047dd39d9f418d5483ed600df',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: 18,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '30',
    name: 'Liquity USD',
    symbol: 'LUSD',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x5f98805A4E8be255a32880FDeC7F6728C6568bA0/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0x5f98805A4E8be255a32880FDeC7F6728C6568bA0',
      [Networks.BASE]: '0x368181499736d0c0CC614DBB145E2EC1AC86b8c6',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '31',
    name: 'DOLA',
    symbol: 'DOLA',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/19191.png',
    addresses: {
      [Networks.ETHEREUM]: '0x865377367054516e17014CcdED1e7d814EDC9ce4',
      [Networks.BASE]: '0x4621b7A9c75199271F773Ebd9A499dbd165c3191',
      // [Networks.BNB]: '0x2F29Bc0FFAF9bff337b31CBe6CB5Fb3bf12e5840',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '32',
    name: 'Pax Dollar',
    symbol: 'USDP',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x8E870D67F660D95d5be530380D0eC0bd388289E1/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0x8E870D67F660D95d5be530380D0eC0bd388289E1',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '33',
    name: 'First Digital USD',
    symbol: 'FDUSD',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409',
      [Networks.BASE]: null,
      // [Networks.BNB]: '0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '34',
    name: 'PayPal USD',
    symbol: 'PYUSD',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x6c3ea9036406852006290770BEdFcAbA0e23A0e8/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0x6c3ea9036406852006290770BEdFcAbA0e23A0e8',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 6,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '35',
    name: 'Ondo US Dollar Yield',
    symbol: 'USDY',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x96F6eF951840721AdBF46Ac996b59E0235CB985C/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0x96F6eF951840721AdBF46Ac996b59E0235CB985C',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '36',
    name: 'GHO',
    symbol: 'GHO',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f',
      [Networks.BASE]: '0x6Bb7a212910682DCFdbd5BCBb3e28FB4E8da10Ee',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '37',
    name: 'AUSD',
    symbol: 'AUSD',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/32864.png',
    addresses: {
      [Networks.ETHEREUM]: '0x00000000eFE302BEAA2b3e6e1b18d08D69a9012a',
      [Networks.BASE]: null,
      // [Networks.BNB]: '0x00000000eFE302BEAA2b3e6e1b18d08D69a9012a',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 6,
      [Networks.BASE]: null,
      // [Networks.BNB]: 6,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '38',
    name: 'Function',
    symbol: 'FBTC',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/32306.png',
    addresses: {
      [Networks.ETHEREUM]: '0xC96dE26018A54D51c097160568752c4E3BD6C364',
      [Networks.BASE]: '0xC96dE26018A54D51c097160568752c4E3BD6C364',
      // [Networks.BNB]: '0xC96dE26018A54D51c097160568752c4E3BD6C364',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 8,
      [Networks.BASE]: 8,
      // [Networks.BNB]: 8,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '39',
    name: 'Universal BTC',
    symbol: 'uniBTC',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/36175.png',
    addresses: {
      [Networks.ETHEREUM]: '0x004e9c3ef86bc1ca1f0bb5c7662861ee93350568',
      [Networks.BASE]: '0x93919784C523f39CACaa98Ee0a9d96c3F32b593e',
      // [Networks.BNB]: '0x6B2a01A5f79dEb4c2f3c0eDa7b01DF456FbD726a',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 8,
      [Networks.BASE]: 8,
      // [Networks.BNB]: 8,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '40',
    name: 'BounceBit BTC',
    symbol: 'BBTC',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/31369.png',
    addresses: {
      [Networks.ETHEREUM]: '0xF5e11df1ebCf78b6b6D26E04FF19cD786a1e81dC',
      [Networks.BASE]: null,
      // [Networks.BNB]: '0xF5e11df1ebCf78b6b6D26E04FF19cD786a1e81dC',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '41',
    name: 'Kraken Wrapped Bitcoin',
    symbol: 'kBTC',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/33513.png',
    addresses: {
      [Networks.ETHEREUM]: '0x73E0C0d45E048D25Fc26Fa3159b0aA04BfA4Db98',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: '0x73E0C0d45E048D25Fc26Fa3159b0aA04BfA4Db98',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 8,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: 8,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '42',
    name: 'ether.fi Staked BTC',
    symbol: 'eBTC',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x657e8C867D8B37dCC18fA4Caead9C45EB088C642/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0x657e8C867D8B37dCC18fA4Caead9C45EB088C642',
      [Networks.BASE]: '0x657e8C867D8B37dCC18fA4Caead9C45EB088C642',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: '0x657e8C867D8B37dCC18fA4Caead9C45EB088C642',
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 8,
      [Networks.BASE]: 8,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: 8,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '43',
    name: 'teleBTC',
    symbol: 'teleBTC',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/28970.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: '0xC58C1117DA964aEbe91fEF88f6f5703e79bdA574',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: 8,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '44',
    name: '21.co Wrapped Bitcoin',
    symbol: '21BTC',
    logoUrl:
      'https://assets.coingecko.com/coins/images/34616/standard/64ffa735ee23dbcd35498914_21co_W_Token_v2_21BTC-4.png',
    addresses: {
      [Networks.ETHEREUM]: '0x3f67093dfFD4F0aF4f2918703C92B60ACB7AD78b',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 8,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '45',
    name: 'Wrapped Liquid Staked Ether 2.0',
    symbol: 'wstETH',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0',
      [Networks.BASE]: '0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452',
      // [Networks.BNB]: '0x26c5e01524d2E6280A48F2c50fF6De7e52E9611C',
      [Networks.SCROLL]: '0xf610A9dfB7C89644979b4A0f27063E9e7d7Cda32',
      [Networks.SEPOLIA]: '0xB82381A3fBD3FaFA77B3a7bE693342618240067b',
      [Networks.UNICHAIN]: '0xc02fE7317D4eb8753a02c35fe019786854A92001',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: 18,
      [Networks.UNICHAIN]: 18,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '46',
    name: 'Wrapped Beacon ETH',
    symbol: 'WBETH',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xa2E3356610840701BDf5611a53974510Ae27E2e1/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0xa2E3356610840701BDf5611a53974510Ae27E2e1',
      [Networks.BASE]: null,
      // [Networks.BNB]: '0xa2E3356610840701BDf5611a53974510Ae27E2e1',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '47',
    name: 'Wrapped eETH',
    symbol: 'weETH',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xCd5fE23C85820F7B72D0926FC9b05b43E359b7ee/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0xCd5fE23C85820F7B72D0926FC9b05b43E359b7ee',
      [Networks.BASE]: '0x04C0599Ae5A44757c0af6F9eC3b93da8976c150A',
      // [Networks.BNB]: '0x04C0599Ae5A44757c0af6F9eC3b93da8976c150A',
      [Networks.SCROLL]: '0x01f0a31698c4d065659b9bdc21b3610292a1c506',
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: '0x7DCC39B4d1C53CB31e1aBc0e358b43987FEF80f7',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: '0xa3d68b74bf0528fdd07263c60d6488749044914b',
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: 18,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: 18,
    },
  },
  {
    id: '48',
    name: 'Rocket Pool ETH',
    symbol: 'rETH',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/15060.png',
    addresses: {
      [Networks.ETHEREUM]: '0xae78736Cd615f374D3085123A210448E74Fc6393',
      [Networks.BASE]: '0xB6fe221Fe9EeF5aBa221c348bA20A1Bf5e73624c',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: '0x53878B874283351D26d206FA512aEcE1Bef6C0dD',
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '49',
    name: 'Kelp DAO Restaked ETH',
    symbol: 'rsETH',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/29242.png',
    addresses: {
      [Networks.ETHEREUM]: '0xA1290d69c65A6Fe4DF752f95823fae25cB99e5A7',
      [Networks.BASE]: '0x1Bc71130A0e39942a7658878169764Bbd8A45993',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: '0x65421ba909200b81640d98b979d07487c9781b66',
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: '0xc3eACf0612346366Db554C991D7858716db09f58',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: 18,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '50',
    name: 'Kelp DAO Wrapped rsETH',
    symbol: 'wrsETH',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/32690.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: '0xEDfa23602D0EC14714057867A78d01e94176BEA0',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: '0xa25b25548B4C98B0c7d3d27dcA5D5ca743d68b7F',
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: 18,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '51',
    name: 'Mantle Staked Ether',
    symbol: 'mETH',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/29035.png',
    addresses: {
      [Networks.ETHEREUM]: '0xd5F7838F5C461fefF7FE49ea5ebaF7728bB0ADfa',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: '0x072d71b257ECa6B60b5333626F6a55ea1B0c451c',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: 18,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '52',
    name: 'Liquid Staked ETH',
    symbol: 'LsETH',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/23782.png',
    addresses: {
      [Networks.ETHEREUM]: '0x8c1BEd5b9a0928467c9B1341Da1D7BD5e10b6549',
      [Networks.BASE]: '0xB29749498954A3A821ec37BdE86e386dF3cE30B6',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '53',
    name: 'Renzo Restaked ETH',
    symbol: 'ezETH',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xbf5495Efe5DB9ce00f80364C8B423567e58d2110/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0xbf5495Efe5DB9ce00f80364C8B423567e58d2110',
      [Networks.BASE]: '0x2416092f143378750bb29b79eD961ab195CcEea5',
      // [Networks.BNB]: '0x2416092f143378750bb29b79eD961ab195CcEea5',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: '0x2416092f143378750bb29b79eD961ab195CcEea5',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: 18,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '54',
    name: 'StakeWise Staked ETH',
    symbol: 'osETH',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/28476.png',
    addresses: {
      [Networks.ETHEREUM]: '0xf1C9acDc66974dFB6dEcB12aA385b9cD01190E38',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '55',
    name: 'Stader ETHx',
    symbol: 'ETHx',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/27566.png',
    addresses: {
      [Networks.ETHEREUM]: '0xA35b1B31Ce002FBF2058D22F30f95D405200A15b',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '56',
    name: 'Coinbase Wrapped Staked ETH',
    symbol: 'cbETH',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/21535.png',
    addresses: {
      [Networks.ETHEREUM]: '0xBe9895146f7AF43049ca1c1AE358B0541Ea49704',
      [Networks.BASE]: '0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '57',
    name: 'Frax Staked Ether',
    symbol: 'sfrxETH',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/23177.png',
    addresses: {
      [Networks.ETHEREUM]: '0xac3E018457B222d93114458476f3E3416Abbe38F',
      [Networks.BASE]: '0x1f55a02A049033E3419a8E2975cF3F572F4e6E9A',
      // [Networks.BNB]: '0x3Cd55356433C89E50DC51aB07EE0fa0A95623D53',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '58',
    name: 'Frax Ether',
    symbol: 'frxETH',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/23225.png',
    addresses: {
      [Networks.ETHEREUM]: '0x5E8422345238F34275888049021821E8E08CAa1f',
      [Networks.BASE]: '0xF010a7c8877043681D59AD125EbF575633505942',
      // [Networks.BNB]: '0x64048A7eEcF3a2F1BA9e144aAc3D7dB6e58F555e',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '59',
    name: 'pufETH',
    symbol: 'pufETH',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xD9A442856C234a39a81a089C06451EBAa4306a72/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0xD9A442856C234a39a81a089C06451EBAa4306a72',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]:null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '60',
    name: 'xPufETH',
    symbol: 'xPufETH',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xD9A442856C234a39a81a089C06451EBAa4306a72/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0xD7D2802f6b19843ac4DfE25022771FD83b5A7464',
      [Networks.BASE]: '0x23dA5F2d509cb43A59d43C108a43eDf34510eff1',
      // [Networks.BNB]: '0x64274835D88F5c0215da8AADd9A5f2D2A2569381',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '61',
    name: 'Restaked Swell Ethereum',
    symbol: 'rswETH',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xFAe103DC9cf190eD75350761e95403b7b8aFa6c0/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0xFAe103DC9cf190eD75350761e95403b7b8aFa6c0',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '62',
    name: 'Swell Ethereum',
    symbol: 'swETH',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xf951E335afb289353dc249e82926178EaC7DEd78/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0xf951E335afb289353dc249e82926178EaC7DEd78',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '63',
    name: 'Wrapped Origin Ether',
    symbol: 'WOETH',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/24278.png',
    addresses: {
      [Networks.ETHEREUM]: '0xDcEe70654261AF21C44c093C300eD3Bb97b78192',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '64',
    name: 'Origin Ether',
    symbol: 'oETH',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/24277.png',
    addresses: {
      [Networks.ETHEREUM]: '0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '65',
    name: 'Super OETH',
    symbol: 'superOETHb',
    logoUrl: 'https://assets.coingecko.com/coins/images/39828/standard/Super_OETH.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: '0xDBFeFD2e8460a6Ee4955A68582F85708BAEA60A3',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: 18,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '66',
    name: 'Renzo Restaked LST',
    symbol: 'pzETH',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/32298.png',
    addresses: {
      [Networks.ETHEREUM]: '0x8c9532a60E0E7C6BbD2B2c1303F63aCE1c3E9811',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: '0x9cb41CD74D01ae4b4f640EC40f7A60cA1bCF83E7',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: 18,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '67',
    name: 'Ankr Staked ETH',
    symbol: 'ankrETH',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xE95A203B1a91a908F9B9CE46459d101078c2c3cb/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0xE95A203B1a91a908F9B9CE46459d101078c2c3cb',
      [Networks.BASE]: null,
      // [Networks.BNB]: '0xe05a08226c49b636acf99c40da8dc6af83ce5bb3',
      [Networks.SCROLL]: '0x12D8CE035c5DE3Ce39B1fDD4C1d5a745EAbA3b8C',
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: 18,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '68',
    name: 'Ripple USD',
    symbol: 'RLUSD',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/34387.png',
    addresses: {
      [Networks.ETHEREUM]: '0x8292Bb45bf1Ee4d140127049757C2E0fF06317eD',
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '69',
    name: 'Hyperliquid',
    symbol: 'HYPE',
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/32196.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: ZERO_ETHEREUM_ADDRESS,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '70',
    name: 'Staked HYPE',
    symbol: 'stHYPE',
    logoUrl: 'https://hyperevmscan.io/token/images/stHYPE_64.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0xfFaa4a3D97fE9107Cef8a3F48c069F577Ff76cC1',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '71',
    name: 'Staked HYPE Shares',
    symbol: 'wstHYPE',
    logoUrl: 'https://hyperevmscan.io/token/images/stHYPE_64.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x94e8396e0869c9F2200760aF0621aFd240E1CF38',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '72',
    name: 'Unit Bitcoin',
    symbol: 'UBTC',
    logoUrl: 'https://assets.coingecko.com/coins/images/55066/standard/ubtc.jpg',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x9FDBdA0A5e284c32744D2f17Ee5c74B284993463',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 8,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '73',
    name: 'Unit Ethereum',
    symbol: 'UETH',
    logoUrl: 'https://assets-cdn.trustwallet.com/blockchains/ethereum/info/logo.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0xBe6727B535545C67d5cAa73dEa54865B92CF7907',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '74',
    name: 'Kinetiq Staked HYPE',
    symbol: 'kHYPE',
    logoUrl: 'https://assets.coingecko.com/coins/images/67388/standard/khype.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0xfD739d4e423301CE9385c1fb8850539D657C296D',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '75',
    name: 'Looped HYPE',
    symbol: 'LHYPE',
    logoUrl: 'https://assets.coingecko.com/coins/images/54816/standard/loopedhype_logo_transparent.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x5748ae796AE46A4F1348a1693de4b50560485562',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '76',
    name: 'Relend Network USDC',
    symbol: 'rUSDC',
    logoUrl: 'https://assets.coingecko.com/coins/images/66543/standard/rUSDC-hyper.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x9ab96A4668456896d45c301Bc3A15Cee76AA7B8D',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 6,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '77',
    name: 'Hyper USD',
    symbol: 'USDHL',
    logoUrl: 'https://assets.coingecko.com/coins/images/66679/standard/usdhl.jpg',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0xb50A96253aBDF803D85efcDce07Ad8becBc52BD5',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 6,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '78',
    name: 'Hyperbeat USDT',
    symbol: 'hbUSDT',
    logoUrl: 'https://static.images.dropstab.com/images/hyperbeat-usdt.jpg',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x5e105266db42f78FA814322Bce7f388B4C2e61eb',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '79',
    name: 'Felix feUSD',
    symbol: 'feUSD',
    logoUrl: 'https://static.images.dropstab.com/images/felix-feusd.jpg',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x02c6a2fA58cC01A18B8D9E00eA48d65E4dF26c70',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '80',
    name: 'Theo Short Duration US Treasury Fund',
    symbol: 'thBILL',
    logoUrl: 'https://assets.coingecko.com/coins/images/67650/standard/thBILL.png',
    addresses: {
      [Networks.ETHEREUM]: '0x5FA487BCa6158c64046B2813623e20755091DA0b',
      [Networks.BASE]: '0xfDD22Ce6D1F66bc0Ec89b20BF16CcB6670F55A5a',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0xfDD22Ce6D1F66bc0Ec89b20BF16CcB6670F55A5a',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 6,
      [Networks.BASE]: 6,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 6,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '81',
    name: 'Unit Solana',
    symbol: 'USOL',
    logoUrl: 'https://assets-cdn.trustwallet.com/blockchains/solana/info/logo.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x068f321Fa8Fb9f0D135f290Ef6a3e2813e1c8A29',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 9,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '82',
    name: 'Wrapped HYPE',
    symbol: 'WHYPE',
    logoUrl: 'https://assets.coingecko.com/coins/images/54469/standard/_UP3jBsi_400x400.jpg',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x5555555555555555555555555555555555555555',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '83',
    name: 'Hyperbeat Ultra uBTC',
    symbol: 'hbBTC',
    logoUrl: 'https://hyperevmscan.io/token/images/hbBTC.svg',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0xc061d38903b99aC12713B550C2CB44B221674F94',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: null,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 8,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '84',
    name: 'Aerodrome Finance',
    symbol: 'AERO',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/base/assets/0x940181a94A35A4569E4529A3CDfB74e38FD98631/logo.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: '0x940181a94A35A4569E4529A3CDfB74e38FD98631',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: 18,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '85',
    name: 'Bridged USDC (Base)',
    symbol: 'USDbC',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/base/assets/0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA/logo.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: 6,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '86',
    name: 'Virtuals Protocol',
    symbol: 'VIRTUAL',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/base/assets/0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b/logo.png',
    addresses: {
      [Networks.ETHEREUM]: '0x44ff8620b8cA30902395A7bD3F2407e1A091BF73',
      [Networks.BASE]: '0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '87',
    name: 'Monwell',
    symbol: 'WELL',
    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/base/assets/0xA88594D404727625A9437C3f886C7643872296AE/logo.png',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: '0xa88594d404727625a9437c3f886c7643872296ae',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: 18,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '88',
    name: 'Metronome Synth USD',
    symbol: 'msUSD',
    logoUrl: 'https://assets.smold.app/api/token/8453/0x526728dbc96689597f85ae4cd716d4f7fccbae9d/logo.svg',
    addresses: {
      [Networks.ETHEREUM]: '0xab5eB14c09D416F0aC63661E57EDB7AEcDb9BEfA',
      [Networks.BASE]: '0x526728DBc96689597F85ae4cd716d4f7fCcBAE9d',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.BASE]: 18,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '90',
    name: 'Overnight.fi USD',
    symbol: 'USD+',
    logoUrl: 'https://assets.smold.app/api/token/8453/0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376/logo.svg',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: '0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376',
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.BASE]: 6,
      // [Networks.BNB]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
  },
  {
    id: '91',
    name: 'USDT0',
    symbol: 'USDT0',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: '0x9151434b16b9763660705744891fA906F660EcC5',
      [Networks.HYPER_EVM]: '0xB8CE59FC3717ada4C02eaDF9682A9e934F625ebb',
      [Networks.PLASMA]: '0xb8ce59fc3717ada4c02eadf9682a9e934f625ebb',
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: 6,
      [Networks.HYPER_EVM]: 6,
      [Networks.PLASMA]: 6,
    },
    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/38517.png',
  },
  {
    id: '92',
    name: 'World Liberty Financial',
    symbol: 'WLFI',
    addresses: {
      [Networks.ETHEREUM]: '0xdA5e1988097297dCdc1f90D4dFE7909e847CBeF6',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },

    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0xdA5e1988097297dCdc1f90D4dFE7909e847CBeF6/logo.png',
  },
  {
    id: '93',
    name: 'Pendle',
    symbol: 'PENDLE',
    addresses: {
      [Networks.ETHEREUM]: '0x808507121b80c02388fad14726482e061b8da827',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0xA99F6e6785Da0F5d6fB42495Fe424BCE029Eeb3E',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0xd6eb81136884713e843936843e286fd2a85a205a',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },

    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x808507121B80c02388fAd14726482e061B8da827/logo.png',
  },
  {
    id: '94',
    name: 'Metamask USD',
    symbol: 'mUSD',
    addresses: {
      [Networks.ETHEREUM]: '0xacA92E438df0B2401fF60dA7E4337B687a2435DA',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 6,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/38167.png',
  },
  {
    id: '95',
    name: 'Hyperliquid USD',
    symbol: 'USDH',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x111111a1a0667d36bD57c0A9f569b98057111111',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 6,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/38331.png',
  },
  {
    id: '96',
    name: 'Plasma',
    symbol: 'XPL',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: ZERO_ETHEREUM_ADDRESS,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: 18,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/36645.png',
  },
  {
    id: '97',
    name: 'Wrapped Plasma',
    symbol: 'WXPL',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: '0x6100E367285b01F48D07953803A2d8dCA5D19873',
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: 18,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/36645.png',
  },
  {
    id: '98',
    name: 'Tether Gold Tokens',
    symbol: 'XAUT0',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0xf4d9235269a96aadafc9adae454a0618ebe37949',
      [Networks.PLASMA]: '0x1b64b9025eebb9a6239575df9ea4b9ac46d4d193',
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 6,
      [Networks.PLASMA]: 6,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/37082.png',
  },
  {
    id: '99',
    name: 'Tether Gold',
    symbol: 'XAUT',
    addresses: {
      [Networks.ETHEREUM]: '0x68749665ff8d2d112fa859aa293f07a622782f38',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 6,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/5176.png',
  },
  {
    id: '100',
    name: 'USDai',
    symbol: 'USDai',
    addresses: {
      [Networks.ETHEREUM]: '0x0A1a1A107E45b7Ced86833863f482BC5f4ed82EF',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: '0x0a1a1a107e45b7ced86833863f482bc5f4ed82ef',
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: 18,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/38562.png',
  },
  {
    id: '101',
    name: 'Staked USDai',
    symbol: 'sUSDai',
    addresses: {
      [Networks.ETHEREUM]: '0x0b2b2b2076d95dda7817e785989fe353fe955ef9',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: '0x0b2b2b2076d95dda7817e785989fe353fe955ef9',
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: 18,
    },

    logoUrl: 'https://assets.coingecko.com/coins/images/55861/standard/sUSDai_Token_Full_Glyph.png',
  },
  {
    id: '102',
    name: 'Staked USDe',
    symbol: 'sUSDe',
    addresses: {
      [Networks.ETHEREUM]: '0x9D39A5DE30e57443BfF2A8307A4256c8797A3497',
      [Networks.SCROLL]: '0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2',
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2',
      [Networks.PLASMA]: '0x211cc4dd073734da055fbf44a2b4667d5e5fe5d2',
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: 18,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: 18,
    },

    logoUrl:
      'https://assets-cdn.trustwallet.com/blockchains/ethereum/assets/0x9D39A5DE30e57443BfF2A8307A4256c8797A3497/logo.png',
  },
  {
    id: '103',
    name: 'Wormhole Bridged HYPE',
    symbol: 'HYPE',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: '0x15d0e0c55a3e7ee67152ad7e89acf164253ff68d',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: 18,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/32196.png',
  },
  {
    id: '104',
    name: 'Hyperbeat x Ether.fi HYPE',
    symbol: 'beHYPE',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0xd8fc8f0b03eba61f64d08b0bef69d80916e5dda9',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://assets.coingecko.com/coins/images/69089/standard/behype.png',
  },
  {
    id: '105',
    name: 'Kinetiq Earn Vault',
    symbol: 'vkHYPE',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x9BA2EDc44E0A4632EB4723E81d4142353e1bB160',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://assets.coingecko.com/coins/images/69439/standard/vkhype.png',
  },
  {
    id: '106',
    name: 'Kintsu Staked Hype',
    symbol: 'sHYPE',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0xbef0142a0955a7d5dcce5c2a13fb84e332669d2d',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://assets.coingecko.com/coins/images/69398/standard/sHYPE_Token_Large.png',
  },
  {
    id: '107',
    name: 'Hyperpie Staked mHYPE',
    symbol: 'mHYPE',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0xdabb040c428436d41cecd0fb06bcfdbaad3a9aa8',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://assets.coingecko.com/coins/images/55442/standard/Hyperpie__mHYPE.png',
  },
  {
    id: '108',
    name: 'Liquid HYPE Yield',
    symbol: 'liquidHYPE',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x441794d6a8f9a3739f5d4e98a728937b33489d29',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://assets.coingecko.com/coins/images/68444/standard/liquidhype.png',
  },
  {
    id: '109',
    name: 'Hyperbeat Ultra HYPE',
    symbol: 'hbHYPE',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x96c6cbb6251ee1c257b2162ca0f39aa5fa44b1fb',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://assets.coingecko.com/coins/images/67160/standard/hyperbeat_hype.jpg',
  },
  {
    id: '110',
    name: 'USDtb',
    symbol: 'USDtb',
    addresses: {
      [Networks.ETHEREUM]: '0xc139190f447e929f090edeb554d95abb8b18ac1c',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://assets.coingecko.com/coins/images/52804/standard/76357aa8-4ef7-446c-bad3-a3f944eeec7a.jpeg',
  },
  {
    id: '111',
    name: 'Falcon USD',
    symbol: 'USDf',
    addresses: {
      [Networks.ETHEREUM]: '0xfa2b947eec368f42195f24f36d2af29f7c24cec2',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/35721.png',
  },
  {
    id: '112',
    name: 'Global Dollar',
    symbol: 'USDG',
    addresses: {
      [Networks.ETHEREUM]: '0xe343167631d89b6ffc58b88d6b7fb0228795491d',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 6,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/33793.png',
  },
  {
    id: '113',
    name: 'Usual USD',
    symbol: 'USD0',
    addresses: {
      [Networks.ETHEREUM]: '0x73a15fed60bf67631dc6cd7bc5b6e8da8190acf5',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0x758a3e0b1f842c9306b783f8a4078c6c8c03a270',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/32307.png',
  },
  {
    id: '114',
    name: 'Resolv USD',
    symbol: 'USR',
    addresses: {
      [Networks.ETHEREUM]: '0x66a1e37c9b0eaddca17d3662d6c05f4decf3e110',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0x35e5db674d8e93a03d814fa0ada70731efe8a4b9',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: '0x0ad339d66bf4aed5ce31c64bc37b3244b6394a77',
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: 18,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/32873.png',
  },
  {
    id: '115',
    name: 'Satoshi Stablecoin V2',
    symbol: 'satUSD',
    addresses: {
      [Networks.ETHEREUM]: '0x1958853a8be062dc4f401750eb233f5850f0d0d2',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0x70654aad8b7734dc319d0c3608ec7b32e03fa162',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://assets.coingecko.com/coins/images/37760/standard/Instagram_post_-_25.png',
  },
  {
    id: '116',
    name: 'StraitsX USD',
    symbol: 'XUSD',
    addresses: {
      [Networks.ETHEREUM]: '0xc08e7e23c235073c6807c2efe7021304cb7c2815',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/32372.png',
  },
  {
    id: '117',
    name: 'Resupply USD',
    symbol: 'reUSD',
    addresses: {
      [Networks.ETHEREUM]: '0x57ab1e0003f623289cd798b1824be09a793e4bec',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://assets.coingecko.com/coins/images/54836/standard/reusd-icon-black-200px.png',
  },
  {
    id: '118',
    name: 'USDA',
    symbol: 'USDA',
    addresses: {
      [Networks.ETHEREUM]: '0x0000206329b97db379d5e1bf586bbdb969c63274',
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: '0x0000206329b97db379d5e1bf586bbdb969c63274',
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: 18,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: 18,
      [Networks.UNICHAIN]: null,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },

    logoUrl: 'https://s2.coinmarketcap.com/static/img/coins/128x128/35965.png',
  },
  {
    id: '119',
    name: 'Unichain Bridged WBTC',
    symbol: 'WBTC',
    addresses: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: '0x927b51f251480a681271180da4de28d44ec4afb8',
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    decimals: {
      [Networks.ETHEREUM]: null,
      [Networks.SCROLL]: null,
      [Networks.SEPOLIA]: null,
      [Networks.BASE]: null,
      [Networks.UNICHAIN]: 8,
      [Networks.HYPER_EVM]: null,
      [Networks.PLASMA]: null,
    },
    logoUrl: 'https://assets.smold.app/api/token/130/0x927b51f251480a681271180da4de28d44ec4afb8/logo.svg',
  },
];
