export enum EnvKey {
  API_URL = 'API_URL',
  INDEXER_URL = 'INDEXER_URL',
  ENVIRONMENT = 'ENVIRONMENT',
  PORT = 'PORT',
  UNKEY_ROOT_KEY = 'UNKEY_ROOT_KEY',
  DOCS_API_KEY = 'DOCS_API_KEY',
  AUTH_CACHE_TTL = 'AUTH_CACHE_TTL',
}
